import {products,getProduct,getVariant,availableFinishes,finishes,orientations,mountings,furniture,mechanisms,guides,profiles,sources} from '../systems-data.js';
import {recommend,evaluate,STATUS,dimensionLabels} from './engine.js';
import {configurationId} from './quote.js';
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const stepNames=['Kierunek','Montaż','Dno','Wymiary','Rozwiązanie','Wykończenie','Twoja konfiguracja'];
export const icon=kind=>'<svg viewBox="0 0 72 72" fill="none" aria-hidden="true"><rect x="13" y="8" width="46" height="55" rx="1" stroke="#68745f" stroke-width="2"/>'+
(kind==='vertical'?'<path d="M16 15h40M16 20h40M16 25h40M16 30h40M16 35h40" stroke="#a7b196" stroke-width="2"/><path d="M36 33v23m-6-7 6 7 6-7" stroke="#344f17" stroke-width="2"/>':
kind==='horizontal'?'<path d="M20 12v46M25 12v46M30 12v46M35 12v46" stroke="#a7b196" stroke-width="2"/><path d="M32 38h20m-7-6 7 6-7 6" stroke="#344f17" stroke-width="2"/>':
kind==='inside'?'<path d="M19 13v44M53 13v44" stroke="#a8c323" stroke-width="5"/><path d="M25 29h22M25 35h22" stroke="#b1b9a5" stroke-width="2"/>':
kind==='outside'?'<path d="M11 7v57M61 7v57M11 7h50" stroke="#a8c323" stroke-width="5"/><path d="M19 29h34M19 35h34" stroke="#b1b9a5" stroke-width="2"/>':
kind==='with-bottom'?'<path d="M18 13v43h36V13M18 56h36" stroke="#4a4f53" stroke-width="2.4"/><path d="M21 51h30" stroke="#d2071d" stroke-width="6"/>':
kind==='without-bottom'?'<path d="M18 13v43M54 13v43M18 13h36" stroke="#4a4f53" stroke-width="2.4"/><path d="M21 55h30" stroke="#d2071d" stroke-width="2" stroke-dasharray="4 4"/>':
'<path d="M16 29h40M16 44h40" stroke="#a4af99" stroke-width="2"/>')+'</svg>';
const choice=(s,field,id,title,sub)=>'<button type="button" class="choice'+(field==='furniture'?' wide':'')+'" data-choice="'+field+'" data-value="'+id+'" aria-pressed="'+(s[field]===id)+'">'+icon(id)+'<span><strong>'+title+'</strong><small>'+sub+'</small></span></button>';
const unknownChoice=(s,field)=>'<button class="unknown" data-choice="'+field+'" data-value="unknown" aria-pressed="'+(s[field]==='unknown')+'">Nie wiem, pomóż mi wybrać<span aria-hidden="true">'+(s[field]==='unknown'?'✓':'+')+'</span></button>';
const help=text=>'<details class="why"><summary>Dlaczego o to pytamy?</summary><p>'+text+'</p></details>';
export function canNext(s){if(s.mode==='expert')return false;if(s.step===1)return Boolean(s.orientation);if(s.step===2)return Boolean(s.mounting);if(s.step===3)return Boolean(s.furniture);if(s.step===5)return Boolean(s.selectedProduct);return true;}
export function dimensionFields(s){return '<div class="dimension-fields">'+['width','height','depth'].map(k=>'<div class="dimension-field"><label for="dim-'+k+'">'+dimensionLabels[k]+'<button class="mini-link" data-clear-dim="'+k+'" type="button">Nie znam wymiaru</button></label><div class="input-wrap"><input type="number" id="dim-'+k+'" data-dimension="'+k+'" inputmode="numeric" min="1" max="10000" step="1" placeholder="Do ustalenia" value="'+(s.dimensions[k]??'')+'" aria-describedby="error-'+k+'"><span>mm</span></div><p class="field-error" id="error-'+k+'"></p></div>').join('')+'</div>';}
function finishPreview(product,orientation){
 const list=availableFinishes(product,orientation);if(!list.length)return '';
 return '<div class="rec-finishes" aria-label="Dostępne kolory"><span class="rec-finishes-label">Dostępne kolory</span><div class="rec-finish-list">'+list.map(f=>'<div class="rec-finish"><span class="rec-finish-swatch '+f.material+'" style="--swatch:'+f.color+'"></span><span class="rec-finish-name">'+escape(f.name)+'</span></div>').join('')+'</div></div>';
}
function rangeGuidance(product,orientation){
 const v=getVariant(product,orientation);if(!v)return '';
 if(v.rangeProfile==='c6')return 'Szer. 200–800 × wys. 350–1050 mm; szer. 801–1100 × wys. 350–700 mm; szer. 1101–1200 × wys. 350–525 mm.';
 if(v.rangeProfile==='c3')return 'Szer. 400–599 × wys. 650–1900 mm; szer. 600–1200 × wys. 650–2200 mm.';
 return '';
}
export function dimensionRangeFeedback(s){
 const candidates=products.filter(p=>(!s.orientation||s.orientation==='unknown'||p.orientations.value.includes(s.orientation))&&(!s.mounting||s.mounting==='unknown'||p.mounting.value===s.mounting));
 return candidates.map(p=>{const v=getVariant(p,s.orientation);if(!v?.rangeProfile)return '';const result=evaluate(p,{...s,finish:null});const errors=result.rejections.filter(x=>x.includes('poza ofertą')||x.includes('maksymalna wysokość')||x.startsWith('Głębokość:')||x.startsWith('Szerokość:')||x.startsWith('Wysokość:'));return '<div class="range-option'+(errors.length?' range-outside':'')+'"><strong>'+escape(p.name)+(errors.length?' — poza zakresem':'')+'</strong><p>'+escape(rangeGuidance(p,s.orientation))+'</p>'+(v.dimensions.depth?.value?.min?'<p>Głębokość: od '+v.dimensions.depth.value.min+' mm.</p>':'')+errors.map(x=>'<p class="range-error">'+escape(x)+'</p>').join('')+'</div>';}).join('');
}
function recommendations(s){
const list=recommend(s),rejected=products.map(p=>evaluate(p,s)).filter(r=>r.status===STATUS.INCOMPATIBLE);
const availableRanges=products.filter(p=>p.orientations.value.includes(s.orientation)&&(!s.mounting||s.mounting==='unknown'||p.mounting.value===s.mounting)).map(p=>[p.name,rangeGuidance(p,s.orientation)]).filter(x=>x[1]);
return(list.length?'<div class="recommendation-list">'+list.map((r,i)=>{
const p=r.product,v=getVariant(p,s.orientation),m=mechanisms[v?.mechanism.value];
return '<article class="rec-card'+(s.selectedProduct===p.id?' selected':'')+'"><button data-product="'+p.id+'" aria-pressed="'+(s.selectedProduct===p.id)+'"><span class="rec-tag">'+(i===0?'Najlepszy punkt wyjścia':'Alternatywa '+i)+'</span><span class="rec-head"><h3>'+p.name+'</h3><span class="rec-check">'+(s.selectedProduct===p.id?'✓':'')+'</span></span><p>'+p.short+'</p></button>'+finishPreview(p,s.orientation)+'<details><summary>Dlaczego ten wariant?</summary><ul>'+r.reasons.map(x=>'<li>'+escape(x)+'</li>').join('')+'</ul><p class="spec-detail">'+p.description+'</p><p>'+(m?m.description:'Dokładną drogę prowadzenia dobierzemy z INTAGO.')+' '+(v?.mechanism.status!=='verified'?'Schemat poglądowy. ':'')+'Miejsce zajmowane przez mechanizm: do potwierdzenia.</p><ul>'+r.missing.map(x=>'<li>'+escape(x)+'</li>').join('')+'</ul></details><p class="verification">Wymaga potwierdzenia szczegółów</p></article>';
}).join('')+'</div>':'<div class="none"><strong>Podane wymiary są poza zakresem dostępnych systemów.</strong><p>Możliwe zakresy:</p><ul>'+availableRanges.map(x=>'<li><strong>'+escape(x[0])+':</strong> '+escape(x[1])+'</li>').join('')+'</ul><button class="btn subtle" data-action="manual">Przygotuj zapytanie</button></div>')+
(rejected.length?'<details class="rejected" '+(rejected.some(r=>r.rejections.some(x=>x.includes('poza ofertą')||x.includes('maksymalna wysokość')))?'open':'')+'><summary>Dlaczego pozostałe nie pasują? ('+rejected.length+')</summary>'+rejected.map(r=>'<p><strong>'+r.product.name+'</strong></p><ul>'+r.rejections.map(x=>'<li>'+escape(x)+'</li>').join('')+(rangeGuidance(r.product,s.orientation)?'<li><strong>Zakres:</strong> '+escape(rangeGuidance(r.product,s.orientation))+'</li>':'')+'</ul>').join('')+'</details>':'')+
(list.length?'<button class="text-button" data-action="manual">Wolę poprosić o dobór indywidualny</button>':'');
}
function finishPanel(s){const list=availableFinishes(getProduct(s.selectedProduct),s.orientation);
return list.length?'<div class="finish-grid">'+list.map(f=>'<button class="finish '+f.material+'" data-finish="'+f.id+'" aria-pressed="'+(s.finish===f.id)+'" style="--swatch:'+f.color+'"><span class="swatch"></span><strong>'+f.name+'</strong><small>'+(f.code||'Wykończenie materiału')+'</small></button>').join('')+'</div><button class="unknown" data-action="unknown-finish" aria-pressed="'+!s.finish+'">Wykończenie ustalę później<span>'+(s.finish?'＋':'✓')+'</span></button><p class="field-help">Kolory z oferty tego wariantu INTAGO. Podgląd nie zastępuje próbki materiału; dostępność zestawu potwierdzimy przy wycenie.</p>':
'<div class="hint"><span class="hint-marker">i</span><p><strong>Wykończenie dobierzemy wspólnie.</strong><br>Nie mamy potwierdzonej palety dla tego wariantu. Możesz przejść dalej — zapiszemy kolor jako „do ustalenia”.</p></div>';}
function summary(s){
const p=getProduct(s.selectedProduct),v=getVariant(p,s.orientation),f=finishes[s.finish],r=p?evaluate(p,s):null;
const rows=[['Wariant',p?.name||'Dobór indywidualny'],['Kierunek',orientations[s.orientation]||'Do ustalenia'],['Montaż',mountings[s.mounting]||'Do ustalenia'],['Dno szafki',furniture[s.furniture]||'Do ustalenia'],['Wymiary S × W × G',['width','height','depth'].map(k=>s.dimensions[k]??'?').join(' × ')+' mm'],['Wykończenie',f?f.name+(f.code?' / '+f.code:''):'Do ustalenia'],['Mechanizm',v?.mechanism.status==='verified'?mechanisms[v.mechanism.value].name:'Do potwierdzenia']];
return '<p class="configuration-id">'+configurationId(s)+'</p><dl class="summary-list">'+rows.map(([k,val])=>'<div><dt>'+k+'</dt><dd>'+escape(val)+'</dd></div>').join('')+'</dl>'+
'<details class="summary-details" open><summary>Dlaczego ten wariant?</summary><ul>'+(r?.reasons||['Konfigurację przekażemy do indywidualnego doboru.']).map(x=>'<li>'+escape(x)+'</li>').join('')+'</ul></details>'+
'<details class="summary-details" open><summary>Co potwierdzimy przed realizacją?</summary><ul>'+(r?.missing||['Wariant, wykonalność, pomiar, mechanizm i wykończenie.']).map(x=>'<li>'+escape(x)+'</li>').join('')+'</ul></details>'+
'<div class="summary-buttons"><button class="btn primary" data-action="quote">Poproś o wycenę ↗</button><div class="row"><button class="btn subtle" data-action="copy">Kopiuj konfigurację</button><button class="btn subtle" data-action="print">Drukuj kartę</button></div><button class="text-button" data-action="export-svg">Pobierz rysunek SVG</button></div>';}
const rangeLabel=r=>r.min===undefined?'do '+r.max:r.max===undefined?'od '+r.min:r.min+'–'+r.max;
function expert(s){return '<div class="step-meta"><span class="eyebrow">DLA PROFESJONALISTY</span></div><div class="question"><h2 id="wizard-title" tabindex="-1">Znasz system?<br>Zacznij tutaj.</h2><p class="intro">Wybierz wariant. Przejdziesz od razu do pomiaru. Reguły doboru są takie same jak w doradcy.</p>'+products.map(p=>'<article class="expert-card"><h3>'+p.name+'<button data-expert="'+p.id+'">Wybierz ↗</button></h3><p>'+p.orientations.value.map(o=>orientations[o]).join(' / ')+' · '+mountings[p.mounting.value]+'</p><details><summary>Dane i źródła</summary><p>Prowadnice: '+guides[p.guideId].name+'</p>'+Object.entries(p.variants).map(([orientation,v])=>'<p><strong>'+orientations[orientation]+'</strong> · '+(v.mechanism.status==='verified'?mechanisms[v.mechanism.value].name:'Mechanizm do potwierdzenia')+' · Profil: '+(v.profile.status==='verified'?profiles[v.profile.value].name:'do potwierdzenia')+'</p><ul>'+Object.entries(v.dimensions).map(([key,f])=>'<li>'+dimensionLabels[key]+': '+(f.status==='verified'?rangeLabel(f.value)+' mm':'do potwierdzenia')+'</li>').join('')+'</ul>'+(sources[v.sourceReference]?.url?'<a target="_blank" rel="noopener" href="'+sources[v.sourceReference].url+'">Karta INTAGO ↗</a>':'<p>Szczegóły zlecenia do potwierdzenia.</p>')).join('')+'</details></article>').join('')+'</div><button class="text-button" data-action="expert">Wróć do doradcy</button>';}
export function renderWizard(s){
if(s.mode==='expert')return expert(s);
const titles=['Jak ma otwierać się Twoja roleta?','Gdzie mają być prowadnice?','Czy szafka ma dno?','Zmierz wnętrze swojej szafki.','Zacznij od tych rozwiązań.','Nadaj rolecie swój charakter.','Twój mebel. Twoja roleta.'];
const intros=['Wybierz kierunek i od razu sprawdź go na modelu. Przeciągnij uchwyt, aby zajrzeć do środka.','Zdecyduj, czy krawędzie korpusu mają pozostać widoczne. Różnicę zobaczysz także w przekroju.','Wybierz konstrukcję korpusu. Dolna płyta pojawi się lub zniknie także na modelu.','Mierz w milimetrach, między <strong>wewnętrznymi</strong> ściankami. Nie znasz któregoś wymiaru? Ustalimy go później.','Porównaliśmy kierunek, montaż i dostępne zakresy wymiarów. Wybierz punkt wyjścia do wyceny.','Wykończenia z oferty wybranego wariantu. Dotknij próbki, aby zobaczyć zmianę na meblu.','Karta zbiera Twoje wybory i informacje do potwierdzenia przez INTAGO.'];
let content='';
if(s.step===1)content='<div class="choice-grid">'+choice(s,'orientation','vertical','Pionowo','Otwieranie do góry')+choice(s,'orientation','horizontal','Poziomo','Otwieranie na bok')+'</div>'+unknownChoice(s,'orientation')+'<div class="hint"><span class="hint-marker">↗</span><p>Front chowa się w meblu.<br><strong>Przed szafką zostaje wolna przestrzeń.</strong></p></div>';
if(s.step===2)content=s.orientation==='horizontal'?'<div class="stack">'+choice(s,'mounting','inside','Wewnątrz korpusu','Prowadnice TOP-BASIC')+'</div><div class="hint"><span class="hint-marker">i</span><p><strong>Roleta pozioma jest montowana wewnątrz korpusu.</strong><br>Ten sposób montażu ustawiamy automatycznie.</p></div>':'<div class="choice-grid">'+choice(s,'mounting','inside','Wewnątrz','Widoczne krawędzie korpusu')+choice(s,'mounting','outside','Na korpusie','Prowadnice na krawędziach')+'</div><button class="text-button compare-button" data-action="compare" aria-pressed="false">Pokaż różnicę w montażu ↗</button>'+unknownChoice(s,'mounting')+help('Położenie prowadnic wpływa na wygląd frontu i dobór systemu. Pomiar do zapytania zbieramy wewnątrz korpusu; wymiar cięcia potwierdzi INTAGO.');
if(s.step===3)content=s.orientation==='horizontal'?'<div class="stack bottom-choice">'+choice(s,'furniture','with-bottom','Z dnem w szafce','Wymagane dla rolety poziomej')+'</div><div class="hint"><span class="hint-marker">i</span><p><strong>Roleta pozioma wymaga dna szafki.</strong><br>Ta opcja jest ustawiana automatycznie.</p></div>':'<div class="stack bottom-choice">'+choice(s,'furniture','with-bottom','Z dnem w szafce','Dolna płyta zamyka korpus')+choice(s,'furniture','without-bottom','Bez dna w szafce','Przestrzeń pozostaje otwarta od dołu')+'</div>';
if(s.step===4)content='<button class="btn subtle measure-start" data-action="measure"><span>Pomóż mi zmierzyć</span><span aria-hidden="true">↗</span></button>'+dimensionFields(s)+'<div id="range-feedback" aria-live="polite"><p><strong>Zakresy dla wybranego kierunku i montażu</strong></p>'+dimensionRangeFeedback(s)+'</div>'+help('To wymiary wnętrza potrzebne do przygotowania zapytania, a nie wymiary cięcia rolety. Prowadnice i mechanizm zajmą część przestrzeni. Ich odsadzenia ustalimy dla wybranego zestawu.');
if(s.step===5)content=recommendations(s);
if(s.step===6)content=finishPanel(s)+'<div class="hint"><span class="hint-marker">↗</span><p><strong>Zajrzyj do mechanizmu.</strong><br>Przełącz widok nad modelem, aby zobaczyć, gdzie chowa się płaszcz rolety.</p></div>';
if(s.step===7)content=summary(s);
const next=['Dobierz roletę','Dalej','Dalej','Sprawdź rozwiązania','Wybierz wykończenie','Zobacz konfigurację'];
return '<div class="step-meta"><span class="eyebrow">'+stepNames[s.step-1].toUpperCase()+'</span><span>0'+s.step+' / 07</span></div><section class="question"><h2 id="wizard-title" tabindex="-1">'+titles[s.step-1]+'</h2><p class="intro">'+intros[s.step-1]+'</p>'+content+'</section><div class="actions">'+(s.step>1?'<button class="prev" data-action="prev">← '+(s.step===7?'Zmień konfigurację':'Wstecz')+'</button>':'<span class="micro muted">Zacznij od kierunku</span>')+(s.step<7?'<button class="btn primary" data-action="next" '+(canNext(s)?'':'disabled')+'>'+next[s.step-1]+' <span aria-hidden="true">→</span></button>':'<button class="text-button" data-action="edit-start">Zmień od początku</button>')+'</div><div class="saved-note" id="save-note">Twoje wybory zostają na tym urządzeniu</div>';
}
